[package]
name = "main"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.90"
uniform-logic-rs = { git = "https://github.com/saiblo/uniform-logic-rs.git", branch = "main" }
